export const todosObj = [
  {
    id: 1,
    title: "Fix homepage UI",
    description: "Adjust padding and fix responsiveness for mobile view.",
    createdAt: new Date("2025-02-15"),
    status: "in-progress",
  },
  {
    id: 2,
    title: "Integrate payment gateway",
    description: "Connect Stripe API for secure transactions.",
    createdAt: new Date("2025-02-14"),
    status: "done",
  },
  {
    id: 3,
    title: "Optimize product image loading",
    description: "Implement lazy loading for product images.",
    createdAt: new Date("2025-02-16"),
    status: "in-progress",
  },
  {
    id: 4,
    title: "Refactor cart logic",
    description: "Improve state management for cart updates.",
    createdAt: new Date("2025-02-13"),
    status: "done",
  },
  {
    id: 5,
    title: "Implement dark mode",
    description: "Allow users to switch between light and dark themes.",
    createdAt: new Date("2025-02-18"),
    status: "in-progress",
  },
  {
    id: 6,
    title: "Setup CI/CD pipeline",
    description: "Automate deployment process using GitHub Actions.",
    createdAt: new Date("2025-02-10"),
    status: "done",
  },
  {
    id: 7,
    title: "Write unit tests for authentication",
    description: "Ensure login and registration flows work correctly.",
    createdAt: new Date("2025-02-12"),
    status: "in-progress",
  },
  {
    id: 8,
    title: "Improve accessibility",
    description: "Add ARIA attributes and improve keyboard navigation.",
    createdAt: new Date("2025-02-11"),
    status: "done",
  },
  {
    id: 9,
    title: "Enhance search functionality",
    description: "Implement filters and sorting options for product search.",
    createdAt: new Date("2025-02-17"),
    status: "in-progress",
  },
  {
    id: 10,
    title: "Optimize database queries",
    description: "Refactor slow SQL queries to improve performance.",
    createdAt: new Date("2025-02-09"),
    status: "done",
  },
  {
    id: 11,
    title: "Add social login",
    description: "Enable users to log in using Google and Facebook.",
    createdAt: new Date("2025-02-19"),
    status: "in-progress",
  },
  {
    id: 12,
    title: "Implement order tracking",
    description: "Allow users to track their order status in real time.",
    createdAt: new Date("2025-02-16"),
    status: "in-progress",
  },
  {
    id: 13,
    title: "Improve email notifications",
    description: "Enhance email templates for order confirmation and updates.",
    createdAt: new Date("2025-02-08"),
    status: "done",
  },
  {
    id: 14,
    title: "Migrate to a new hosting provider",
    description: "Move servers to AWS for better scalability.",
    createdAt: new Date("2025-02-07"),
    status: "done",
  },
  {
    id: 15,
    title: "Fix broken links in footer",
    description: "Ensure all links in the footer are working properly.",
    createdAt: new Date("2025-02-20"),
    status: "in-progress",
  },
  {
    id: 16,
    title: "Implement wishlist feature",
    description: "Allow users to save products to their wishlist.",
    createdAt: new Date("2025-02-21"),
    status: "in-progress",
  },
  {
    id: 17,
    title: "Add multi-language support",
    description: "Enable users to switch between different languages.",
    createdAt: new Date("2025-02-22"),
    status: "in-progress",
  },
  {
    id: 18,
    title: "Enhance product reviews",
    description: "Allow users to upload images with their reviews.",
    createdAt: new Date("2025-02-23"),
    status: "in-progress",
  },
  {
    id: 19,
    title: "Optimize checkout process",
    description: "Reduce the number of steps required to complete a purchase.",
    createdAt: new Date("2025-02-24"),
    status: "done",
  },
  {
    id: 20,
    title: "Improve site speed",
    description: "Optimize assets and enable caching for better performance.",
    createdAt: new Date("2025-02-25"),
    status: "in-progress",
  },
];
